### ISSUE TITLE
Server responds with 502

### ISSUE THREAD

**Issue by juliariec** [healeycodes/real-rainy-mood#13]
The website shows "Loading.." but nothing displays.

The console has the following error statements:
`Failed to load resource: the server responded with a status of 502`
`Uncaught (in promise) HTTPError: 502`

with the Netlify `/functions/weather` endpoint sending the following error message:

`{ "errorType":"TypeError",
"errorMessage":"Cannot read property '0' of undefined",
"trace":["TypeError: Cannot read property '0' of undefined","    
at Runtime.exports.handler (/var/task/weather.js:11:45)","    
at processTicksAndRejections (internal/process/task_queues.js:97:5)"] }`

**Comment by healeycodes** [comment]
Hi @juliariec!

Thanks for spotting this.

It looks like Netlify depreciated (https://answers.netlify.com/t/x-forwarded-host/7104/9) the header I was using to get the client's ip.

The client ip header with longterm support is `x-nf-client-connection-ip`.

#17 fixed this and is now deployed at https://real-rainy-mood.netlify.app/

**Comment by juliariec** [comment]
@healeycodes I'm happy that it's up and running again!
